config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "home#index"

  get 'home/index'

  get 'about' => 'pages#about'
  get 'information' => 'pages#information'
  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments, only: [:create]
  end

  resource :terms
  resource :abouts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :users
  has_many :comments, dependent: :destroy
  validates :title, length: { maximum: 140 }, presence: true
  validates :text, length: { maximum: 4000 }, presence: true


  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, length: { maximum: 4000 }, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  def index
      @articles = Article.all
      @articles = Article.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])

  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.author = current_user.username
    @comment.save
    redirect_to article_path(@article)
  end
private
  def comment_params
  params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def information
end

def about
end

end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def show
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/abouts/show.html.erb
<h1>About Us</h1>
<p>Here we are...</p>
<p>If you here...</p>
<p>Our blog is very...</p>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>Edit Article</h3>

      <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
        <p>
          <%= f.label :title, class:"fw-semibold" %><br />
          <%= f.text_field :title %>
        </p>

        <p>
          <%= f.label :text, class:"fw-semibold" %><br />
          <%= f.text_area :text %>
        </p>

        <p>
          <%= f.submit class:"btn btn-outline-warning" %>
        </p>

      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= t("articles.articles")%></h1>

      <p><%= link_to 'New article', article_path([:new]) %></p>
      <p><%= link_to 'Main menu', home_index_path([:index]) %></p>

      <hr />
      <hr />

      <% @articles.each do |article| %>
      <h3>
        <%= article.title %>
      </h3>
      <p>
        <%= article.text %>
      </p>
       <p>
        <%= link_to 'Show', article_path(article), class:"link-warning" %> ||
        <%= link_to 'Edit', edit_article_path(article), class:"link-warning" %>
        <%= button_to 'Delete', article_path(article), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class:"btn btn-outline-danger" %>

        </p>
        <hr />
       <% end %>
       <!-- <a href="/articles">Show all articles</a> -->

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>New Article</h2>

      <%= form_for :article, url: articles_path do |f| %>
      <% if @article && @article.errors.any? %>
      <p>
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </p>
      <% end %>
      <div class="row g-3 align-items-center">
        <div class="col-auto">
        <p>
          <%= f.label :title, class:"col-auto" %><br />
          <%= f.text_field :title, class:"form-control" %>
        </p>
        </div>
      </div>
        <p>
          <%= f.label :text, class:"fw-semibold" %><br />
          <%= f.text_area :text, class:"form-control" %>
        </p>

        <p>
          <%= f.submit class:"btn btn-outline-success" %>
        </p>

      <% end %>

    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p><%= link_to 'Show all articles', articles_path %></p>

      <h1><%= @article.title %></h1>
      <p>
        <%= @article.text %>
      </p>
      <h5>All comments</h5>
        <% @article.comments.each do |comment| %>
        <p><strong> <i><p><%= comment.author %>:</i></strong> <br/></p>
          <%= comment.body %><hr/>
          <% end %><hr/>
      <h5>Add comment</h5>

      <p>
        <%= form_for([@article, @article.comments.build]) do |f| %>
          <p>
            <%= f.label :body, class:"fw-semibold" %><br />
            <%= f.text_area :body %>
          </p>

          <p>
            <%= f.submit class:"btn btn-outline-warning" %>
          </p>

        <% end %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="fs-4">
<h3><%= t("contacts.contact_us") %></h3>

<%= form_for :contact, url: contacts_path do |f| %>
<% if @contact && @contact.errors.any? %>
<p>
  <ul>
  <% @contact.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
</p>
<% end %>
  <p>
    <%= f.label :email, class:"fw-semibold" %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message, class:"fw-semibold" %><br />
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Send message', class:"btn btn-outline-success"%>
  </p>

<% end %>
      </div>
    </div>
  </div>
</div>

app/views/terms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Our terms</h1>
      <p>If you on this page...</p>
    </div>
  </div>
</div>